create table if not exists public.question_banks (
  id bigint generated by default as identity primary key,
  title text not null check (length(trim(title)) between 2 and 200),
  subject text not null check (length(trim(subject)) between 2 and 120),
  description text not null default '',
  owner_id uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.question_bank_items (
  id bigint generated by default as identity primary key,
  bank_id bigint not null references public.question_banks(id) on delete cascade,
  title text not null check (length(trim(title)) between 2 and 200),
  prompt text not null check (length(trim(prompt)) between 5 and 10000),
  response_type text not null check (response_type in ('written','link','file_upload')),
  marks integer not null check (marks > 0 and marks <= 10000),
  difficulty text not null default 'medium' check (difficulty in ('easy','medium','hard')),
  is_required boolean not null default true,
  written_answer_type text check (written_answer_type in ('short','long')),
  word_limit integer check (word_limit is null or (word_limit > 0 and word_limit <= 10000)),
  allowed_file_types text[],
  maximum_file_size_mb integer check (maximum_file_size_mb is null or (maximum_file_size_mb > 0 and maximum_file_size_mb <= 500)),
  link_guidance text,
  sort_order integer not null default 0 check (sort_order >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (response_type = 'written' and written_answer_type is not null and allowed_file_types is null and maximum_file_size_mb is null)
    or (response_type = 'link' and written_answer_type is null and word_limit is null and allowed_file_types is null and maximum_file_size_mb is null)
    or (response_type = 'file_upload' and written_answer_type is null and word_limit is null and coalesce(array_length(allowed_file_types, 1), 0) > 0 and maximum_file_size_mb is not null)
  )
);

create index if not exists question_banks_owner_id_idx on public.question_banks(owner_id);
create index if not exists question_bank_items_bank_id_idx on public.question_bank_items(bank_id);

alter table public.question_banks enable row level security;
alter table public.question_bank_items enable row level security;

create policy question_banks_admin_all on public.question_banks
for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()) and owner_id = (select auth.uid()));

create policy question_bank_items_admin_all on public.question_bank_items
for all to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));