create schema if not exists private;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  full_name text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.assessments (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  instructions text not null default '',
  status text not null default 'draft' check (status in ('draft','published','closed')),
  duration_minutes integer not null default 45 check (duration_minutes between 1 and 1440),
  total_points integer not null default 100 check (total_points >= 0),
  available_from timestamptz not null,
  available_until timestamptz not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (available_until > available_from)
);

create table if not exists public.assessment_questions (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.assessments(id) on delete cascade,
  title text not null,
  prompt text not null,
  points integer not null default 0 check (points >= 0),
  sort_order integer not null default 0,
  response_type text not null default 'written' check (response_type in ('written','link','file_upload')),
  is_required boolean not null default true,
  written_answer_type text check (written_answer_type in ('short','long')),
  word_limit integer,
  allowed_file_types text[],
  maximum_file_size_mb integer,
  link_guidance text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,
  assessment_id bigint not null references public.assessments(id) on delete cascade,
  auth_user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text not null,
  phone text,
  status text not null default 'not_started' check (status in ('not_started','in_progress','submitted','reviewed')),
  score numeric,
  decision text not null default 'pending' check (decision in ('pending','shortlisted','on_hold','rejected')),
  started_at timestamptz,
  expires_at timestamptz,
  submitted_at timestamptz,
  last_saved_at timestamptz,
  source text not null default 'manual',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (assessment_id, email)
);

create table if not exists public.candidate_responses (
  id bigint generated by default as identity primary key,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  question_id bigint not null references public.assessment_questions(id) on delete cascade,
  response_text text,
  response_url text,
  file_path text,
  file_name text,
  file_size bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (candidate_id, question_id)
);

create index if not exists candidates_assessment_id_idx on public.candidates(assessment_id);
create index if not exists candidates_auth_user_id_idx on public.candidates(auth_user_id);
create index if not exists candidates_email_idx on public.candidates(lower(email));
create index if not exists assessment_questions_assessment_id_idx on public.assessment_questions(assessment_id);
create index if not exists candidate_responses_candidate_id_idx on public.candidate_responses(candidate_id);
create index if not exists candidate_responses_question_id_idx on public.candidate_responses(question_id);

alter table public.admin_profiles enable row level security;
alter table public.assessments enable row level security;
alter table public.assessment_questions enable row level security;
alter table public.candidates enable row level security;
alter table public.candidate_responses enable row level security;

create or replace function private.is_admin()
returns boolean language sql stable security definer set search_path = ''
as $$ select exists(select 1 from public.admin_profiles p where p.user_id = (select auth.uid()) and p.is_active); $$;
revoke all on function private.is_admin() from public;
grant execute on function private.is_admin() to authenticated;

create or replace function private.candidate_email_matches(candidate_email text)
returns boolean language sql stable security invoker set search_path = ''
as $$ select (select auth.uid()) is not null and lower(coalesce((select auth.jwt()->>'email'),'')) = lower(candidate_email); $$;
revoke all on function private.candidate_email_matches(text) from public;
grant execute on function private.candidate_email_matches(text) to authenticated;

drop policy if exists admin_profiles_self on public.admin_profiles;
create policy admin_profiles_self on public.admin_profiles for select to authenticated using (user_id = (select auth.uid()));

drop policy if exists assessments_access on public.assessments;
create policy assessments_access on public.assessments for select to authenticated using (
  (select private.is_admin()) or (
    status = 'published' and exists(select 1 from public.candidates c where c.assessment_id = assessments.id and (select private.candidate_email_matches(c.email)))
  )
);
drop policy if exists assessments_admin_insert on public.assessments;
create policy assessments_admin_insert on public.assessments for insert to authenticated with check ((select private.is_admin()));
drop policy if exists assessments_admin_update on public.assessments;
create policy assessments_admin_update on public.assessments for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists assessments_admin_delete on public.assessments;
create policy assessments_admin_delete on public.assessments for delete to authenticated using ((select private.is_admin()));

drop policy if exists questions_access on public.assessment_questions;
create policy questions_access on public.assessment_questions for select to authenticated using (
  (select private.is_admin()) or exists(
    select 1 from public.candidates c join public.assessments a on a.id=c.assessment_id
    where c.assessment_id=assessment_questions.assessment_id and a.status='published' and (select private.candidate_email_matches(c.email))
  )
);
drop policy if exists questions_admin_insert on public.assessment_questions;
create policy questions_admin_insert on public.assessment_questions for insert to authenticated with check ((select private.is_admin()));
drop policy if exists questions_admin_update on public.assessment_questions;
create policy questions_admin_update on public.assessment_questions for update to authenticated using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists questions_admin_delete on public.assessment_questions;
create policy questions_admin_delete on public.assessment_questions for delete to authenticated using ((select private.is_admin()));

drop policy if exists candidates_access on public.candidates;
create policy candidates_access on public.candidates for select to authenticated using ((select private.is_admin()) or (select private.candidate_email_matches(email)));
drop policy if exists candidates_admin_insert on public.candidates;
create policy candidates_admin_insert on public.candidates for insert to authenticated with check ((select private.is_admin()));
drop policy if exists candidates_update on public.candidates;
create policy candidates_update on public.candidates for update to authenticated
using ((select private.is_admin()) or (select private.candidate_email_matches(email)))
with check ((select private.is_admin()) or (select private.candidate_email_matches(email)));
drop policy if exists candidates_admin_delete on public.candidates;
create policy candidates_admin_delete on public.candidates for delete to authenticated using ((select private.is_admin()));

drop policy if exists responses_access on public.candidate_responses;
create policy responses_access on public.candidate_responses for select to authenticated using (
  (select private.is_admin()) or exists(select 1 from public.candidates c where c.id=candidate_responses.candidate_id and (select private.candidate_email_matches(c.email)))
);
drop policy if exists responses_insert on public.candidate_responses;
create policy responses_insert on public.candidate_responses for insert to authenticated with check (
  (select private.is_admin()) or exists(
    select 1 from public.candidates c join public.assessment_questions q on q.id=candidate_responses.question_id
    where c.id=candidate_responses.candidate_id and q.assessment_id=c.assessment_id and c.status='in_progress' and now()<c.expires_at and (select private.candidate_email_matches(c.email))
  )
);
drop policy if exists responses_update on public.candidate_responses;
create policy responses_update on public.candidate_responses for update to authenticated
using ((select private.is_admin()) or exists(select 1 from public.candidates c where c.id=candidate_responses.candidate_id and c.status='in_progress' and now()<c.expires_at and (select private.candidate_email_matches(c.email))))
with check ((select private.is_admin()) or exists(select 1 from public.candidates c join public.assessment_questions q on q.id=candidate_responses.question_id where c.id=candidate_responses.candidate_id and q.assessment_id=c.assessment_id and c.status='in_progress' and now()<c.expires_at and (select private.candidate_email_matches(c.email))));

create or replace function private.guard_candidate_update()
returns trigger language plpgsql security invoker set search_path = ''
as $$
declare a public.assessments;
begin
  if (select private.is_admin()) then new.updated_at=now(); return new; end if;
  if not (select private.candidate_email_matches(old.email)) then raise exception 'Not authorized'; end if;
  if new.assessment_id is distinct from old.assessment_id or new.email is distinct from old.email or new.full_name is distinct from old.full_name
     or new.score is distinct from old.score or new.decision is distinct from old.decision then raise exception 'Protected fields cannot be changed'; end if;
  select * into a from public.assessments where id=old.assessment_id;
  if old.status='not_started' and new.status='in_progress' then
    if a.status<>'published' or now()<a.available_from or now()>a.available_until then raise exception 'Assessment unavailable'; end if;
    new.auth_user_id=(select auth.uid()); new.started_at=now(); new.expires_at=least(a.available_until,now()+make_interval(mins=>a.duration_minutes)); new.last_saved_at=now();
  elsif old.status='in_progress' and new.status='submitted' then
    if now()>old.expires_at then raise exception 'Assessment time expired'; end if;
    new.submitted_at=now(); new.last_saved_at=now();
  elsif new.status is distinct from old.status then raise exception 'Invalid status transition';
  end if;
  new.updated_at=now(); return new;
end; $$;
drop trigger if exists guard_candidate_update on public.candidates;
create trigger guard_candidate_update before update on public.candidates for each row execute function private.guard_candidate_update();

grant select, insert, update, delete on public.assessments, public.assessment_questions, public.candidates, public.candidate_responses to authenticated;
grant select on public.admin_profiles to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets(id,name,public,file_size_limit) values ('candidate-submissions','candidate-submissions',false,52428800)
on conflict(id) do update set public=false,file_size_limit=52428800;
drop policy if exists candidate_files_insert on storage.objects;
create policy candidate_files_insert on storage.objects for insert to authenticated with check (bucket_id='candidate-submissions' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists candidate_files_select on storage.objects;
create policy candidate_files_select on storage.objects for select to authenticated using (bucket_id='candidate-submissions' and ((storage.foldername(name))[1]=(select auth.uid())::text or (select private.is_admin())));
drop policy if exists candidate_files_update on storage.objects;
create policy candidate_files_update on storage.objects for update to authenticated using (bucket_id='candidate-submissions' and (storage.foldername(name))[1]=(select auth.uid())::text) with check (bucket_id='candidate-submissions' and (storage.foldername(name))[1]=(select auth.uid())::text);
