alter table public.assessments
  add column if not exists due_date timestamptz;

create table if not exists public.exam_attempts (
  id uuid primary key default gen_random_uuid(),
  candidate_id bigint not null unique references public.candidates(id) on delete cascade,
  assessment_id bigint not null references public.assessments(id) on delete cascade,
  student_id uuid not null references auth.users(id) on delete restrict,
  started_at timestamptz not null,
  ends_at timestamptz not null,
  submitted_at timestamptz,
  status text not null default 'in_progress'
    check (status in ('in_progress', 'submitted', 'auto_submitted')),
  submission_reason text
    check (submission_reason in ('manual', 'timeout')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > started_at),
  check (
    (status = 'in_progress' and submitted_at is null and submission_reason is null)
    or
    (status in ('submitted', 'auto_submitted') and submitted_at is not null and submission_reason is not null)
  )
);

create index if not exists exam_attempts_assessment_student_idx
  on public.exam_attempts(assessment_id, student_id);
create index if not exists exam_attempts_student_id_idx
  on public.exam_attempts(student_id);
create index if not exists exam_attempts_expiry_idx
  on public.exam_attempts(ends_at)
  where status = 'in_progress';

alter table public.candidate_responses
  add column if not exists attempt_id uuid references public.exam_attempts(id) on delete cascade,
  add column if not exists client_revision bigint not null default 0
    check (client_revision >= 0);

create index if not exists candidate_responses_attempt_id_idx
  on public.candidate_responses(attempt_id);

create table if not exists public.grading_queue (
  id bigint generated by default as identity primary key,
  attempt_id uuid not null unique references public.exam_attempts(id) on delete cascade,
  assessment_id bigint not null references public.assessments(id) on delete cascade,
  candidate_id bigint not null references public.candidates(id) on delete cascade,
  status text not null default 'pending'
    check (status in ('pending', 'in_review', 'completed')),
  enqueued_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists grading_queue_status_enqueued_idx
  on public.grading_queue(status, enqueued_at);
create index if not exists grading_queue_assessment_id_idx
  on public.grading_queue(assessment_id);
create index if not exists grading_queue_candidate_id_idx
  on public.grading_queue(candidate_id);

-- Preserve attempts and responses created before Phase 4.
insert into public.exam_attempts (
  candidate_id,
  assessment_id,
  student_id,
  started_at,
  ends_at,
  submitted_at,
  status,
  submission_reason
)
select
  c.id,
  c.assessment_id,
  c.auth_user_id,
  coalesce(c.started_at, c.submitted_at - interval '1 minute'),
  greatest(
    coalesce(c.started_at, c.submitted_at - interval '1 minute') + interval '1 second',
    coalesce(
      c.expires_at,
      c.submitted_at,
      coalesce(c.started_at, c.submitted_at - interval '1 minute') + interval '1 minute'
    )
  ),
  case
    when c.status in ('submitted', 'reviewed') then coalesce(c.submitted_at, c.last_saved_at, c.started_at)
    else null
  end,
  case
    when c.status in ('submitted', 'reviewed') then 'submitted'
    else 'in_progress'
  end,
  case when c.status in ('submitted', 'reviewed') then 'manual' else null end
from public.candidates c
where c.auth_user_id is not null
  and (c.started_at is not null or c.submitted_at is not null)
on conflict (candidate_id) do nothing;

update public.candidate_responses r
set attempt_id = a.id
from public.exam_attempts a
where a.candidate_id = r.candidate_id
  and r.attempt_id is null;

insert into public.grading_queue(attempt_id, assessment_id, candidate_id)
select a.id, a.assessment_id, a.candidate_id
from public.exam_attempts a
where a.status in ('submitted', 'auto_submitted')
on conflict (attempt_id) do nothing;

alter table public.exam_attempts enable row level security;
alter table public.grading_queue enable row level security;

drop policy if exists exam_attempts_select on public.exam_attempts;
create policy exam_attempts_select
on public.exam_attempts
for select
to authenticated
using (
  (select private.is_admin())
  or student_id = (select auth.uid())
);

drop policy if exists grading_queue_admin_select on public.grading_queue;
create policy grading_queue_admin_select
on public.grading_queue
for select
to authenticated
using ((select private.is_admin()));

grant select on public.exam_attempts, public.grading_queue to authenticated;
grant select, insert, update on public.exam_attempts, public.grading_queue to service_role;
grant usage, select on sequence public.grading_queue_id_seq to service_role;

-- Candidate writes now go through authenticated server routes and transactional
-- functions. Direct browser mutations are intentionally removed.
revoke insert, update, delete on public.exam_attempts from authenticated;
revoke insert, update, delete on public.grading_queue from authenticated;
revoke insert, update, delete on public.candidate_responses from authenticated;

create or replace function public.finalize_exam_attempt_internal(
  p_attempt_id uuid,
  p_reason text
)
returns public.exam_attempts
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_attempt public.exam_attempts;
  v_status text;
begin
  if p_reason not in ('manual', 'timeout') then
    raise exception 'Invalid submission reason';
  end if;

  select *
  into v_attempt
  from public.exam_attempts
  where id = p_attempt_id
  for update;

  if not found then
    raise exception 'Attempt not found';
  end if;

  if v_attempt.status <> 'in_progress' then
    return v_attempt;
  end if;

  v_status := case when p_reason = 'timeout' then 'auto_submitted' else 'submitted' end;

  update public.exam_attempts
  set
    status = v_status,
    submission_reason = p_reason,
    submitted_at = clock_timestamp(),
    updated_at = clock_timestamp()
  where id = p_attempt_id
  returning * into v_attempt;

  perform set_config('app.phase4_internal', 'on', true);
  update public.candidates
  set
    status = 'submitted',
    submitted_at = v_attempt.submitted_at,
    last_saved_at = coalesce(last_saved_at, v_attempt.submitted_at),
    updated_at = v_attempt.submitted_at
  where id = v_attempt.candidate_id
    and status in ('not_started', 'in_progress');

  insert into public.grading_queue(attempt_id, assessment_id, candidate_id)
  values (v_attempt.id, v_attempt.assessment_id, v_attempt.candidate_id)
  on conflict (attempt_id) do nothing;

  return v_attempt;
end;
$$;

revoke all on function public.finalize_exam_attempt_internal(uuid, text) from public, anon, authenticated;
grant execute on function public.finalize_exam_attempt_internal(uuid, text) to service_role;

create or replace function public.start_exam_attempt_internal(
  p_candidate_id bigint,
  p_student_id uuid,
  p_email text
)
returns table (
  attempt_id uuid,
  candidate_id bigint,
  assessment_id bigint,
  attempt_status text,
  started_at timestamptz,
  ends_at timestamptz,
  server_time timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_candidate public.candidates;
  v_assessment public.assessments;
  v_attempt public.exam_attempts;
  v_now timestamptz := clock_timestamp();
  v_closes_at timestamptz;
begin
  select *
  into v_candidate
  from public.candidates
  where id = p_candidate_id
  for update;

  if not found
    or v_candidate.auth_user_id is distinct from p_student_id
    or lower(v_candidate.email) <> lower(trim(p_email))
    or v_candidate.is_active is not true
    or (v_candidate.access_expires_at is not null and v_candidate.access_expires_at <= v_now)
  then
    raise exception 'Candidate assignment is unavailable';
  end if;

  select *
  into v_assessment
  from public.assessments
  where id = v_candidate.assessment_id;

  v_closes_at := coalesce(v_assessment.available_until, v_assessment.due_date);

  select *
  into v_attempt
  from public.exam_attempts a
  where a.candidate_id = p_candidate_id;

  if found then
    if v_attempt.status = 'in_progress' and v_now >= v_attempt.ends_at then
      v_attempt := public.finalize_exam_attempt_internal(v_attempt.id, 'timeout');
    end if;
    return query select
      v_attempt.id,
      v_attempt.candidate_id,
      v_attempt.assessment_id,
      v_attempt.status,
      v_attempt.started_at,
      v_attempt.ends_at,
      v_now;
    return;
  end if;

  if v_candidate.status <> 'not_started'
    or v_assessment.status <> 'published'
    or (v_assessment.available_from is not null and v_now < v_assessment.available_from)
    or v_closes_at is null
    or v_now >= v_closes_at
  then
    raise exception 'Assessment is not available to start';
  end if;

  insert into public.exam_attempts(
    candidate_id,
    assessment_id,
    student_id,
    started_at,
    ends_at
  )
  values (
    v_candidate.id,
    v_candidate.assessment_id,
    p_student_id,
    v_now,
    least(
      v_closes_at,
      v_now + make_interval(mins => v_assessment.duration_minutes)
    )
  )
  returning * into v_attempt;

  perform set_config('app.phase4_internal', 'on', true);
  update public.candidates
  set
    status = 'in_progress',
    started_at = v_attempt.started_at,
    expires_at = v_attempt.ends_at,
    last_saved_at = v_attempt.started_at,
    updated_at = v_attempt.started_at
  where id = v_candidate.id;

  return query select
    v_attempt.id,
    v_attempt.candidate_id,
    v_attempt.assessment_id,
    v_attempt.status,
    v_attempt.started_at,
    v_attempt.ends_at,
    v_now;
end;
$$;

revoke all on function public.start_exam_attempt_internal(bigint, uuid, text) from public, anon, authenticated;
grant execute on function public.start_exam_attempt_internal(bigint, uuid, text) to service_role;

create or replace function public.save_exam_answer_internal(
  p_attempt_id uuid,
  p_student_id uuid,
  p_email text,
  p_question_id bigint,
  p_response_text text,
  p_response_url text,
  p_file_path text,
  p_file_name text,
  p_file_size bigint,
  p_client_revision bigint
)
returns table (
  saved boolean,
  attempt_status text,
  ends_at timestamptz,
  server_time timestamptz,
  saved_at timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_attempt public.exam_attempts;
  v_candidate public.candidates;
  v_question public.assessment_questions;
  v_now timestamptz := clock_timestamp();
  v_saved_at timestamptz;
begin
  select *
  into v_attempt
  from public.exam_attempts
  where id = p_attempt_id
  for update;

  if not found or v_attempt.student_id is distinct from p_student_id then
    raise exception 'Attempt not found';
  end if;

  if p_client_revision < 0 then
    raise exception 'Invalid answer revision';
  end if;

  select *
  into v_candidate
  from public.candidates
  where id = v_attempt.candidate_id;

  if lower(v_candidate.email) <> lower(trim(p_email))
    or v_candidate.auth_user_id is distinct from p_student_id
    or v_candidate.is_active is not true
    or (v_candidate.access_expires_at is not null and v_candidate.access_expires_at <= v_now)
  then
    raise exception 'Candidate assignment is unavailable';
  end if;

  if v_attempt.status <> 'in_progress' or v_now >= v_attempt.ends_at then
    if v_attempt.status = 'in_progress' then
      v_attempt := public.finalize_exam_attempt_internal(v_attempt.id, 'timeout');
    end if;
    return query select false, v_attempt.status, v_attempt.ends_at, v_now, null::timestamptz;
    return;
  end if;

  select *
  into v_question
  from public.assessment_questions
  where id = p_question_id
    and assessment_id = v_attempt.assessment_id;

  if not found then
    raise exception 'Question is not part of this assessment';
  end if;

  if v_question.response_type = 'written' then
    if nullif(trim(coalesce(p_response_url, '')), '') is not null or p_file_path is not null then
      raise exception 'Invalid written response';
    end if;
    if v_question.word_limit is not null
      and cardinality(regexp_split_to_array(nullif(trim(coalesce(p_response_text, '')), ''), '\s+')) > v_question.word_limit
    then
      raise exception 'Written response exceeds the word limit';
    end if;
  elsif v_question.response_type = 'link' then
    if nullif(trim(coalesce(p_response_text, '')), '') is not null or p_file_path is not null then
      raise exception 'Invalid link response';
    end if;
    if nullif(trim(coalesce(p_response_url, '')), '') is not null
      and trim(p_response_url) !~* '^https?://[^\s]+$'
    then
      raise exception 'Enter a valid http or https URL';
    end if;
  elsif v_question.response_type = 'file_upload' then
    if nullif(trim(coalesce(p_response_text, '')), '') is not null
      or nullif(trim(coalesce(p_response_url, '')), '') is not null
    then
      raise exception 'Invalid file response';
    end if;
    if p_file_path is not null
      and p_file_path not like (p_student_id::text || '/' || v_candidate.id::text || '/%')
    then
      raise exception 'Invalid file path';
    end if;
    if (p_file_path is null) <> (p_file_name is null)
      or (p_file_path is null) <> (p_file_size is null)
    then
      raise exception 'Incomplete file response';
    end if;
    if p_file_size is not null
      and p_file_size > coalesce(v_question.maximum_file_size_mb, 10)::bigint * 1024 * 1024
    then
      raise exception 'File is too large';
    end if;
    if p_file_name is not null
      and cardinality(v_question.allowed_file_types) > 0
      and not exists (
        select 1
        from unnest(v_question.allowed_file_types) as allowed(extension)
        where lower(trim(leading '.' from allowed.extension))
          = lower(regexp_replace(p_file_name, '^.*\.', ''))
      )
    then
      raise exception 'File type is not allowed';
    end if;
  else
    raise exception 'Unsupported response type';
  end if;

  insert into public.candidate_responses(
    attempt_id,
    candidate_id,
    question_id,
    response_text,
    response_url,
    file_path,
    file_name,
    file_size,
    client_revision,
    updated_at
  )
  values (
    v_attempt.id,
    v_attempt.candidate_id,
    v_question.id,
    nullif(trim(coalesce(p_response_text, '')), ''),
    nullif(trim(coalesce(p_response_url, '')), ''),
    p_file_path,
    p_file_name,
    p_file_size,
    p_client_revision,
    v_now
  )
  on conflict (candidate_id, question_id)
  do update set
    attempt_id = excluded.attempt_id,
    response_text = excluded.response_text,
    response_url = excluded.response_url,
    file_path = excluded.file_path,
    file_name = excluded.file_name,
    file_size = excluded.file_size,
    client_revision = excluded.client_revision,
    updated_at = excluded.updated_at
  where excluded.client_revision >= public.candidate_responses.client_revision
  returning updated_at into v_saved_at;

  if v_saved_at is not null then
    perform set_config('app.phase4_internal', 'on', true);
    update public.candidates
    set last_saved_at = v_saved_at, updated_at = v_saved_at
    where id = v_attempt.candidate_id;
  end if;

  return query select true, v_attempt.status, v_attempt.ends_at, v_now, v_saved_at;
end;
$$;

revoke all on function public.save_exam_answer_internal(uuid, uuid, text, bigint, text, text, text, text, bigint, bigint) from public, anon, authenticated;
grant execute on function public.save_exam_answer_internal(uuid, uuid, text, bigint, text, text, text, text, bigint, bigint) to service_role;

create or replace function public.submit_exam_attempt_internal(
  p_attempt_id uuid,
  p_student_id uuid,
  p_email text
)
returns table (
  attempt_status text,
  submitted_at timestamptz,
  ends_at timestamptz,
  server_time timestamptz
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_attempt public.exam_attempts;
  v_candidate public.candidates;
  v_now timestamptz := clock_timestamp();
  v_missing integer;
  v_reason text;
begin
  select *
  into v_attempt
  from public.exam_attempts
  where id = p_attempt_id
  for update;

  if not found or v_attempt.student_id is distinct from p_student_id then
    raise exception 'Attempt not found';
  end if;

  select *
  into v_candidate
  from public.candidates
  where id = v_attempt.candidate_id;

  if lower(v_candidate.email) <> lower(trim(p_email))
    or v_candidate.auth_user_id is distinct from p_student_id
  then
    raise exception 'Candidate assignment is unavailable';
  end if;

  if v_attempt.status <> 'in_progress' then
    return query select v_attempt.status, v_attempt.submitted_at, v_attempt.ends_at, v_now;
    return;
  end if;

  v_reason := case when v_now >= v_attempt.ends_at then 'timeout' else 'manual' end;

  if v_reason = 'manual' then
    select count(*)
    into v_missing
    from public.assessment_questions q
    where q.assessment_id = v_attempt.assessment_id
      and q.is_required
      and not exists (
        select 1
        from public.candidate_responses r
        where r.attempt_id = v_attempt.id
          and r.question_id = q.id
          and case q.response_type
            when 'written' then nullif(trim(coalesce(r.response_text, '')), '') is not null
            when 'link' then nullif(trim(coalesce(r.response_url, '')), '') is not null
            when 'file_upload' then r.file_path is not null
            else false
          end
      );

    if v_missing > 0 then
      raise exception 'Complete % required task(s)', v_missing;
    end if;
  end if;

  v_attempt := public.finalize_exam_attempt_internal(v_attempt.id, v_reason);
  return query select v_attempt.status, v_attempt.submitted_at, v_attempt.ends_at, v_now;
end;
$$;

revoke all on function public.submit_exam_attempt_internal(uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.submit_exam_attempt_internal(uuid, uuid, text) to service_role;

create or replace function public.auto_submit_expired_attempts()
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_count integer;
begin
  perform set_config('app.phase4_internal', 'on', true);

  with due as (
    select id
    from public.exam_attempts
    where status = 'in_progress'
      and ends_at <= clock_timestamp()
    order by ends_at
    limit 500
    for update skip locked
  ),
  expired as (
    update public.exam_attempts a
    set
      status = 'auto_submitted',
      submission_reason = 'timeout',
      submitted_at = clock_timestamp(),
      updated_at = clock_timestamp()
    from due
    where a.id = due.id
    returning a.id, a.assessment_id, a.candidate_id, a.submitted_at
  ),
  updated_candidates as (
    update public.candidates c
    set
      status = 'submitted',
      submitted_at = e.submitted_at,
      last_saved_at = coalesce(c.last_saved_at, e.submitted_at),
      updated_at = e.submitted_at
    from expired e
    where c.id = e.candidate_id
      and c.status in ('not_started', 'in_progress')
    returning e.id, e.assessment_id, e.candidate_id
  ),
  queued as (
    insert into public.grading_queue(attempt_id, assessment_id, candidate_id)
    select id, assessment_id, candidate_id
    from updated_candidates
    on conflict (attempt_id) do nothing
    returning id
  )
  select count(*) into v_count from expired;

  return v_count;
end;
$$;

revoke all on function public.auto_submit_expired_attempts() from public, anon, authenticated;
grant execute on function public.auto_submit_expired_attempts() to service_role;

-- Existing candidate guards remain useful for admin edits. Phase 4's
-- transactional functions set a transaction-local marker for internal updates.
create or replace function private.guard_candidate_update()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if current_setting('app.phase4_internal', true) = 'on' then
    new.updated_at = coalesce(new.updated_at, now());
    return new;
  end if;

  if (select private.is_admin()) then
    new.updated_at = now();
    return new;
  end if;

  raise exception 'Candidate updates must use the assessment attempt API';
end;
$$;

-- Supabase supports pg_cron. The sweep is idempotent and also runs
-- opportunistically from save/submit routes, so delayed scheduler execution
-- cannot extend an attempt.
create extension if not exists pg_cron with schema pg_catalog;

do $$
declare
  existing_job bigint;
begin
  select jobid into existing_job
  from cron.job
  where jobname = 'phase4-auto-submit-expired-attempts';

  if existing_job is not null then
    perform cron.unschedule(existing_job);
  end if;

  perform cron.schedule(
    'phase4-auto-submit-expired-attempts',
    '10 seconds',
    'select public.auto_submit_expired_attempts();'
  );
end;
$$;
